{{- if .Values.backup-api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-backup-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backup-api
{{- end }}
