apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - patch-replicas.yaml
helmCharts:
  - name: microservices
    repo: file://../../../charts/microservices
    version: 1.0.0
    releaseName: microservices
    namespace: microservices-prod
    valuesFile: values-prod.yaml
