# argocd/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

helmCharts:
  - name: microservices
    repo: file://../../../charts/microservices
    version: 1.0.0
    releaseName: microservices-dev
    namespace: microservices-dev
    valuesFile: values-dev.yaml

patchesStrategicMerge:
  - patch-dev.yaml
