# argocd/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

helmCharts:
  - name: microservices
    repo: file://../../../charts/microservices
    version: 1.0.0
    releaseName: microservices-staging
    namespace: microservices-staging
    valuesFile: values-staging.yaml

patchesStrategicMerge:
  - patch-replicas-staging.yaml  #
