name: Backup API CI/CD

on:
  push:
    paths: ['microservice/backup/**']
  pull_request:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Fix script permissions
        run: bash common/setup.sh
      
      - name: Build with Buildah
        run: |
          cd microservice/backup/docker
          bash ./build.sh

      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh
          syft localhost/backup-api:latest -o cyclonedx-json > sbom.json

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost/backup-api:latest
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Sign with Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-version: 'v2.2.1'
      - run: cosign sign --yes localhost/backup-api:latest
