name: Lint Bash Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  
  workflow_dispatch:  # append to define scripts inputs to avoid errors
    inputs:
      first_arg:  # first input
        description: 'First argument for script'
        required: true
        default: 'hello'
        type: string
      second_arg:  # second input
        description: 'Second argument for script'
        required: true
        default: 'world'
        type: string
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix script permissions
        run: bash common/fix-permissions.sh

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      
      - name: Run shellcheck on scripts
        run: find scripts/ -name '*.sh' -exec shellcheck --severity=error {} +
      
      - name: Run arguments.sh with inputs
        run: bash scripts/basics/arguments.sh ${{ inputs.first_arg }} ${{ inputs.second_arg }}
      
      - name: Run ShellCheck
        run: shellcheck scripts/advanced/day8/*.sh


