name: Lint Bash Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # اضافه کن
    inputs:
      first_arg:  # input اول
        description: 'First argument for script'
        required: true
        default: 'hello'
        type: string
      second_arg:  # input دوم
        description: 'Second argument for script'
        required: true
        default: 'world'
        type: string
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck on scripts
        run: find scripts/ -name '*.sh' -exec shellcheck ##--severity=error {} +
        
